Added disabling & endabling endpoints
cryptic-game/java-backend-dev pull request #221
Opened 2020-11-27 16:48 UTC by Frederik-FJ

**Description**
Added endpoints in the admin panel to enable/disable game endpoints

**Issue**
Closes #36

2020-12-04 19:27 UTC, MarcelCoding requested changes

2020-12-04 19:27 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/AdminPanelConfig.java
> +    @Value("${SERVER_API_URL}")
Add `:` to provide (empty) default value.

2020-12-04 22:49 UTC, MarcelCoding approved these changes

2020-12-08 22:16 UTC, JannikEmmerich approved these changes

2020-12-08 22:27 UTC, MarcelCoding approved these changes

2020-12-09 09:55 UTC, merged